development:
  dialect: postgres
  database: wecarry
  user: wecarry
  password: wecarry
  host: db
  pool: 5

staging:
  url: {{envOr "DATABASE_URL" "postgres://wecarry:wecarry@127.0.0.1:5432/wecarry_staging?sslmode=disable"}}

prod:
  url: {{envOr "DATABASE_URL" "postgres://wecarry:wecarry@127.0.0.1:5432/wecarry_production?sslmode=disable"}}

test:
  dialect: postgres
  database: scrutinizer
  user: scrutinizer
  password: scrutinizer
  host: {{envOr "DOCKER_IP" "localhost"}}
