development:
  dialect: postgres
  database: handcarry
  user: handcarry
  password: handcarry
  host: db
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://handcarry:handcarry@db:5432/handcarry_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://handcarry:handcarry@127.0.0.1:5432/handcarry_production?sslmode=disable"}}
