checks:
  go: true
build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      environment:
        go:
          version: go1.13.5
        variables:
          GO_ENV: scrutinizer
          EMAIL_SERVICE: dummy
          AWS_S3_ENDPOINT: http://localhost:9000
          AWS_S3_ACCESS_KEY_ID: abc123
          AWS_S3_SECRET_ACCESS_KEY: abcd1234
          AWS_S3_DISABLE_SSL: true
          AWS_S3_BUCKET: wca-test-bucket
        docker: true
      tests:
        override:
          - go-scrutinizer-run
          - govet-run
          - golint-run
          -
            command: docker build -t wecarry -f Dockerfile-dev .
          -
            command: buffalo-pop pop migrate up
          -
            command: buffalo test
      services:
        postgres: 11.5
        minio:
          image: silintl/minio-default-server
          ports:
            - 9000
          env:
            MINIO_ACCESS_KEY: abc123
            MINIO_SECRET_KEY: abcd1234
          ramdisks:
            - /data
      commands:


  root_path: './application'
