version: "3.7"

services:
  buffalo:
    build:
      context: ./application
      dockerfile: Dockerfile-dev
    volumes:
      - ./application:/handcarry
    ports:
      - "3000:3000"
    environment:
      ADDR: 0.0.0.0
      HOST: http://handcarry.local:3000
      PORT: 3000
    depends_on:
      - db
    command: buffalo dev

  playground:
    build:
      context: ./application
      dockerfile: Dockerfile-dev
    volumes:
      - ./application:/handcarry
    ports:
      - "8082:3000"
    command: go run gqlgen/server/server.go

  db:
    image: postgres:9.6.13
    environment:
      POSTGRES_USER: handcarry
      POSTGRES_PASSWORD: handcarry
      POSTGRES_DB: handcarry
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080

  phppgadmin:
    restart: always
    image: dockage/phppgadmin:latest
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      - PHP_PG_ADMIN_SERVER_DESC=PostgreSQL
      - PHP_PG_ADMIN_SERVER_HOST=db
      - PHP_PG_ADMIN_SERVER_PORT=5432
      - PHP_PG_ADMIN_SERVER_SSL_MODE=allow
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=handcarry
      - PHP_PG_ADMIN_SERVER_PG_DUMP_PATH=/usr/bin/pg_dump
      - PHP_PG_ADMIN_SERVER_PG_DUMPALL_PATH=/usr/bin/pg_dumpall
      - PHP_PG_ADMIN_DEFAULT_LANG=auto
      - PHP_PG_ADMIN_AUTO_COMPLETE=default on
      - PHP_PG_ADMIN_EXTRA_LOGIN_SECURITY=false
      - PHP_PG_ADMIN_OWNED_ONLY=false
      - PHP_PG_ADMIN_SHOW_COMMENTS=true
      - PHP_PG_ADMIN_SHOW_ADVANCED=false
      - PHP_PG_ADMIN_SHOW_SYSTEM=false
      - PHP_PG_ADMIN_MIN_PASSWORD_LENGTH=1
      - PHP_PG_ADMIN_LEFT_WIDTH=200
      - PHP_PG_ADMIN_THEME=default
      - PHP_PG_ADMIN_SHOW_OIDS=false
      - PHP_PG_ADMIN_MAX_ROWS=30
      - PHP_PG_ADMIN_MAX_CHARS=50
      - PHP_PG_ADMIN_USE_XHTML_STRICT=false
      - PHP_PG_ADMIN_HELP_BASE=http://www.postgresql.org/docs/%s/interactive/
      - PHP_PG_ADMIN_AJAX_REFRESH=3
